apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: app2
  source:
    path: "HelmCharts/MyChart2"
    repoURL: "git@github.com:mikhail-prorekhin/argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_dev.yaml
      parameters:
        - name: "container.image"
          value: prorekhin/k8s_pmv_test_1:version1

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
